---
# https://docs.openshift.com/dedicated/operators/admin/olm-managing-custom-catalogs.html#olm-creating-catalog-from-index_olm-managing-custom-catalogs
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: isas-fsd-catalog
  namespace: openshift-marketplace
  # annotations:
  #   olm.catalogImageTemplate:
  #     "<registry>/<namespace>/<index_image_name>:v{kube_major_version}.{kube_minor_version}.{kube_patch_version}"
spec:
  sourceType: grpc
  grpcPodConfig:
    securityContextConfig: restricted
    extractContent:
      cacheDir: /tmp/cache
      catalogDir: /configs
  # anonymous.apps.t-ocp-its-01.xaas.epfl.ch is a (temporary, from the `.t-` part)
  # mirroring proxy of quay-its.epfl.ch; see https://go.epfl.ch/INC0674050
  image: anonymous.apps.t-ocp-its-01.xaas.epfl.ch/svc0041/isas-fsd-catalog:latest
  displayName: ISAS-FSD Catalog
  publisher: isas-fsd
  updateStrategy:
    registryPoll:
      interval: 20m
