apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: controller-manager-metrics-service
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: nfs-subdir-ext-provisioner-olm
    app.kubernetes.io/part-of: nfs-subdir-ext-provisioner-olm
  name: nfs-ext-olm-controller-manager-metrics-service
  namespace: nfs-subdir-ext-provisioner-olm-system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
