apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: manager-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nfs-subdir-ext-provisioner-olm
    app.kubernetes.io/part-of: nfs-subdir-ext-provisioner-olm
  name: nfs-ext-olm-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nfs-ext-olm-manager-role
subjects:
- kind: ServiceAccount
  name: nfs-ext-olm-controller-manager
  namespace: nfs-ext-olm-system
