apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: controller-manager-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nfs-subdir-ext-provisioner-olm
    app.kubernetes.io/part-of: nfs-subdir-ext-provisioner-olm
  name: nfs-ext-olm-controller-manager
  namespace: nfs-ext-olm-system
